version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #     - redis
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017
  #     - REDIS_ADDR=redis:6379

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru

